services:
  - type: web
    name: botva-installer
    runtime: node
    rootDir: installer
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
